# Generated by Django 4.0.2 on 2022-06-11 10:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_no', models.CharField(default=uuid.uuid4, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='employee/% Y/% m/% d/')),
                ('nationality', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('status', models.IntegerField(choices=[('ACTIVE', 1), ('INACTIVE', 0)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humancapital.company')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_start', models.DateField()),
                ('contract_end', models.DateField()),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humancapital.contracttype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humancapital.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50)),
                ('assetimage', models.ImageField(upload_to='assets/% Y/% m/% d/')),
                ('assettype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humancapital.assettype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humancapital.employee')),
            ],
        ),
    ]
