# Generated by Django 4.0.2 on 2022-06-11 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[('ACTIVE', 1), ('INACTIVE', 0)], default=1),
        ),
    ]
