# Generated by Django 4.0.2 on 2022-06-11 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0002_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assettype',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contracttype',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
