# Generated by Django 4.0.2 on 2022-06-11 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0003_alter_assettype_desc_alter_contracttype_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='assetimage',
            field=models.ImageField(upload_to='assets%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='employee%Y-%m-%d'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(1, 'ACTIVE'), (0, 'INACTIVE')], default=1),
        ),
    ]
