# Generated by Django 4.0.2 on 2022-06-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0004_alter_asset_assetimage_alter_employee_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='<django.db.models.fields.CharField>_<django.db.models.fields.CharField>%Y-%m-%d'),
        ),
    ]
