# Generated by Django 4.0.2 on 2022-06-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0005_alter_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='employee_%Y-%m-%d'),
        ),
    ]
