# Generated by Django 4.0.2 on 2022-06-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0006_alter_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
    ]
