# Generated by Django 4.0.2 on 2022-06-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0008_employee_qid_employee_qid_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateField(editable=False),
        ),
    ]
