# Generated by Django 4.0.2 on 2022-06-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0009_alter_employee_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='created_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to="UploadTo('employee_%Y-%m-%d')"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qid_img',
            field=models.ImageField(blank=True, upload_to="UploadTo('qid_%Y-%m-%d')"),
        ),
    ]
