# Generated by Django 4.0.2 on 2022-06-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0010_alter_employee_created_on_alter_employee_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to="UploadTo('employee')"),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qid_img',
            field=models.ImageField(blank=True, upload_to="UploadTo('QID')"),
        ),
    ]
