# Generated by Django 4.0.2 on 2022-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0011_alter_employee_image_alter_employee_qid_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_end',
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_duration_months',
            field=models.IntegerField(default=36),
        ),
    ]
