# Generated by Django 4.0.2 on 2022-06-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0012_remove_contract_contract_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_duration_months',
        ),
        migrations.AddField(
            model_name='contracttype',
            name='contract_duration_months',
            field=models.IntegerField(default=36),
        ),
    ]
