# Generated by Django 4.0.2 on 2022-06-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0013_remove_contract_contract_duration_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to='Employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qid_img',
            field=models.ImageField(blank=True, upload_to='QID'),
        ),
    ]
