# Generated by Django 4.0.2 on 2022-06-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0014_alter_employee_image_alter_employee_qid_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='owner',
        ),
        migrations.CreateModel(
            name='AssetOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humancapital.asset')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='humancapital.employee')),
            ],
        ),
    ]
