# Generated by Django 4.0.2 on 2022-06-22 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0015_remove_asset_owner_assetowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetowner',
            name='id',
        ),
        migrations.AlterField(
            model_name='assetowner',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='humancapital.asset'),
        ),
    ]
