# Generated by Django 4.0.2 on 2022-06-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humancapital', '0016_remove_assetowner_id_alter_assetowner_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_desc',
            field=models.TextField(blank=True),
        ),
    ]
